version: '3.8'

services:
  todo:
    build: .
    container_name: todo-app
    restart: always
    environment:
      - LOCO_ENV=production
      - DATABASE_URL=sqlite://data/todo.sqlite?mode=rwc
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/usr/app/data
    networks:
      - proxy
    command: start
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo.rule=Host(`todo.traijan.de`)"
      - "traefik.http.routers.todo.entrypoints=websecure"
      - "traefik.http.routers.todo.tls=true"
      - "traefik.http.routers.todo.tls.certresolver=mytlschallenge"
      - "traefik.http.services.todo.loadbalancer.server.port=5150"

networks:
  proxy:
    external: true
