//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod boards;
pub mod comments;
pub mod projects;
pub mod tags;
pub mod time_entries;
pub mod todos;
pub mod todos_tags;
pub mod users;
pub mod users_projects;
