//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::boards::Entity as Boards;
pub use super::projects::Entity as Projects;
pub use super::users::Entity as Users;
pub use super::users_projects::Entity as UsersProjects;
