//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "todos")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub details: Option<String>,
    pub board_id: i32,
    pub position: i32,
    pub locked: bool,
    pub parent_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::boards::Entity",
        from = "Column::BoardId",
        to = "super::boards::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Boards,
    #[sea_orm(has_many = "super::todos_tags::Entity")]
    TodosTags,
    #[sea_orm(has_many = "super::comments::Entity")]
    Comments,
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl Related<super::boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Boards.def()
    }
}

impl Related<super::todos_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TodosTags.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::todos_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::todos_tags::Relation::Todos.def().rev())
    }
}
